version: '3'

services:
  mongo:
    image: mongo:5.0.22-focal
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ruta donde esta el yml del docker-compose\data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27018
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGO_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge